[package]
name = "test_libs"
version = "0.1.0"
authors = ["Ogban <ogbanugot@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openblas-src = "0.7"